Fix link updates
kwilteam/docs pull request #73
Opened 2023-12-20 00:00 UTC by luisgruson

Update links on docs

2023-12-20 00:06 UTC, KwilLuke requested changes

2023-12-20 00:06 UTC, KwilLuke commented on docs/kuneiform/sql-as-understood-by-kwil/scalar-functions.md
> +    name GLOB '*helium*'
Please double check this, not sure if the code block should appear twice.

2023-12-20 15:27 UTC, KwilLuke commented
@luisgruson Can you please double check that **all** the relative links are fixed? I am still seeing quite a few in this PR:
![relative-paths](https://github.com/kwilteam/docs/assets/105600466/dd151f9e-4f59-40ea-adc3-501fdbe7a537)

2023-12-20 15:27 UTC, KwilLuke commented
@luisgruson Can you please double check that **all** the relative links are fixed? I am still seeing quite a few in this PR:
![relative-paths](https://github.com/kwilteam/docs/assets/105600466/dd151f9e-4f59-40ea-adc3-501fdbe7a537)

2023-12-20 16:53 UTC, luisgruson commented
Made the updates to the absolute links. I kept relative links if they tie to assets on the same page (syntax tree)

2024-01-08 17:37 UTC, KwilLuke approved these changes

2024-01-08 17:41 UTC, merged